# Generated by Django 3.0.8 on 2020-08-19 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import login.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sl', 'Sick Leave'), ('al', 'Annual Leave'), ('cl', 'Casual Leave'), ('ml', 'Maternity Leave'), ('pl', 'paternity Leave')], max_length=100)),
                ('applied_on', models.DateField(auto_now=True)),
                ('from_date', models.DateField(validators=[login.validators.validate_fromdate])),
                ('to_date', models.DateField()),
                ('days', models.IntegerField()),
                ('reason', models.TextField()),
                ('emergency_contact', models.CharField(max_length=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    
    ]
