# Generated by Django 3.0.8 on 2020-09-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_apply',
            name='leave_type',
            field=models.CharField(choices=[('sick_leave', 'Sick Leave'), ('annual_leave', 'Annual Leave'), ('casual_leave', 'Casual Leave'), ('maternity_leave', 'Maternity Leave'), ('paternity_leave', 'paternity Leave')], max_length=100),
        ),
    ]
