# Generated by Django 3.0.8 on 2020-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_verifyform_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyform',
            name='image',
            field=models.ImageField(blank=True, default='noimage.jpg', null=True, upload_to=''),
        ),
    ]
