# Generated by Django 3.0.8 on 2020-07-27 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0005_auto_20200721_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='noimage.jpg', upload_to='')),
                ('salutation', models.CharField(max_length=10, null=True)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('age', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=100, null=True)),
                ('contact1', models.CharField(max_length=100, null=True)),
                ('contact2', models.CharField(max_length=100, null=True)),
                ('flag', models.BooleanField(default=False, null=True)),
                ('verified_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Verifyform',
        ),
    ]
