# Generated by Django 3.0.8 on 2020-07-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0006_auto_20200727_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_profile',
            name='flag',
        ),
    ]
