# Generated by Django 3.0.8 on 2020-07-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0007_remove_employee_profile_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='designtaion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee_profile',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_profile',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_profile',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
