# Generated by Django 3.0.8 on 2020-07-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0008_auto_20200727_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_profile',
            old_name='designtaion',
            new_name='designation',
        ),
    ]
