# Generated by Django 3.0.8 on 2020-08-03 07:51

from django.db import migrations, models
import login.validators


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0011_employee_edu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_profile',
            name='age',
            field=models.CharField(max_length=20, null=True, validators=[login.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='contact1',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='contact2',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='employee_profile',
            name='image',
            field=models.ImageField(default='noimage.jpg', null=True, upload_to=''),
        ),
    ]
