# Generated by Django 3.0.8 on 2020-08-03 14:49

from django.db import migrations, models
import login.validators


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0012_auto_20200803_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_edu',
            name='college',
            field=models.CharField(max_length=100, null=True, validators=[login.validators.name_validators]),
        ),
        migrations.AlterField(
            model_name='employee_edu',
            name='specialization',
            field=models.CharField(max_length=100, null=True, validators=[login.validators.name_validators]),
        ),
        migrations.AlterField(
            model_name='employee_edu',
            name='university',
            field=models.CharField(max_length=100, null=True, validators=[login.validators.name_validators]),
        ),
    ]
