# Generated by Django 3.0.8 on 2020-08-18 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verification', '0013_auto_20200803_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_allocate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick_leave', models.IntegerField()),
                ('annual_leave', models.IntegerField()),
                ('casual_leave', models.IntegerField()),
                ('maternity_leave', models.IntegerField()),
                ('paternity_leave', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
