# Generated by Django 3.0.8 on 2020-08-19 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0014_leave_allocate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leave_allocate',
        ),
    ]
