# Generated by Django 3.0.8 on 2020-07-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verify_form',
            new_name='Verifyform',
        ),
    ]
