# Generated by Django 3.0.8 on 2020-07-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_of_joining',
            new_name='joining_date',
        ),
    ]
