# Generated by Django 3.0.8 on 2020-07-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200727_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
